name: CI
on:
  push:
    branches: [ main, develop, release/* ]
  pull_request:
    branches: [ main, release/* ]
defaults:
  run:
    shell: bash
env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: 1.76.0


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          bash script/prepare.sh

      - name: Unit Testing
        run: |
          bash script/start_node.sh
          sleep 10
          bash script/deploy_contract.sh
          bash script/start_spv_server.sh > spv.log 2>&1 &
          sleep 30
          cat spv.log
          python script/reorg.py
      - name: Publish reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jfoa-build-reports-${{ runner.os }}
          path: spv.log